---
abstract: 'A plugin for Nephia that provides JSON Response DSL'
author:
  - 'ytnobody <ytnobody@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.5, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nephia-Plugin-JSON
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Nephia::Plugin::JSON:
    file: lib/Nephia/Plugin/JSON.pm
    version: 0.02
requires:
  JSON: 0
  Nephia: 0.80
  perl: 5.008005
resources:
  bugtracker: https://github.com/nephia/Nephia-Plugin-JSON/issues
  homepage: https://github.com/nephia/Nephia-Plugin-JSON
  repository: git://github.com/nephia/Nephia-Plugin-JSON
version: 0.02
